# Generated by Django 5.1.2 on 2024-10-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="showsession",
            old_name="astronomy_shows",
            new_name="astronomy_show",
        ),
    ]
