# Generated by Django 5.1.2 on 2024-10-12 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="title",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="rows",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(limit_value=0)]
            ),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="seats_in_row",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(limit_value=0)]
            ),
        ),
        migrations.AddConstraint(
            model_name="showsession",
            constraint=models.UniqueConstraint(
                fields=("astronomy_show", "planetarium_dome"), name="unique_show_dome"
            ),
        ),
    ]
