# Generated by Django 5.1.2 on 2024-10-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_rename_astronomy_shows_showsession_astronomy_show"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomytheme",
            old_name="astronomy_shows",
            new_name="astronomy_show",
        ),
        migrations.RenameField(
            model_name="astronomytheme",
            old_name="themes",
            new_name="theme",
        ),
    ]
