# Generated by Django 5.1.2 on 2024-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planetarium",
            "0003_rename_astronomy_shows_astronomytheme_astronomy_show_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="theme",
            field=models.ManyToManyField(
                related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
        migrations.DeleteModel(
            name="AstronomyTheme",
        ),
    ]
